version: '3'

services: 
    php:
        build: 
            context: .
            dockerfile: dockerfile
        ports: 
            - 80:80
        volumes: 
            - ./src:/var/www/html     
            
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - ./db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: example
        command: 
            - "--default-time-zone=Asia/Jakarta"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment: 
            - PMA_ARBITRARY=1
        ports: 
            - 5000:80

volumes: 
    db_data:
